MultiShop/MultiShop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('adminpanel.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MultiShop/base/urls.py
# myapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import signup, index_view, login_view , verify_email  , logoutUser , profile_detail, change_password, home, search
 # template implementation
from .views import products, product_detail , cart , checkout , myAccount , wishlist , contactUs, products_by_category, order_confirmation, add_to_wishlist,remove_from_wishlist, products_by_brand



urlpatterns = [
    path('', home, name='home'),
    path('index/', index_view, name='index'),  

    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('logoutUser/', logoutUser, name='logoutUser'),
    path('verify-email/<str:token>/', verify_email, name='verify_email'),
    path('profile-detail/', profile_detail, name='profile-detail'),
    # path('edit-profile/', editProfile, name='edit-profile'),
    path('change-password/',change_password, name='change-password'),
    path('search/', search, name='search'),

    # Template Implementation
    path('products/', products, name='products'),
    path('product_detail/<int:id>/', product_detail, name='product_detail'),
    path('products/category/<int:category_id>/', products_by_category, name='products_by_category'),
    path('products/brand/<int:brand_id>/', products_by_brand, name='products_by_brand'),
    path('cart', cart , name='cart'),
    path('checkout', checkout , name='checkout'),
    path('order-confirmation', order_confirmation, name='order_confirmation'),
    path('my-account', myAccount , name='my-account'),
    path('wishlist', wishlist, name='wishlist'),
    path('wishlist/add/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/', remove_from_wishlist, name='wishlist_remove'),
    path('contactUs', contactUs, name='contactUs'),






] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MultiShop/base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.utils.crypto import get_random_string
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.core.mail import send_mail
from django.conf import settings
from django.utils import timezone
import datetime
from base.constant import GENDER_CHOICES, PROVINCE_CHOICES, PAYMENT_METHOD_CHOICES, ORDER_CHOICES


class customuser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    father_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    province = models.CharField(max_length=50, choices=PROVINCE_CHOICES)
    city = models.CharField(max_length=50)
    dob = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=20)
    about = models.TextField(max_length=500)
    profile_pic = models.ImageField(upload_to='profile_pic/', null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)
    verification_token = models.CharField(max_length=100, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email
    

    
    def generate_verification_token(self):
        token = get_random_string(length=32)
        self.verification_token = token
        self.save()
        return token

    def send_email_verification(self):
        subject = 'Verify Your Email Address'
        token = self.generate_verification_token()
        message = f'Hi {self.first_name},\n\nPlease click the link below to verify your email address:\n\n' \
                  f'{settings.BASE_URL}/verify-email/{token}/\n\nThank you!'
        send_mail(subject, message, settings.EMAIL_HOST_USER, [self.email])

@receiver(pre_delete, sender=customuser)
def delete_user_image(sender, instance, **kwargs):
    if instance.profile_pic:
        instance.profile_pic.delete(save=False)


class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



    

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    total_quantity = models.PositiveIntegerField()
    available_quantity = models.PositiveIntegerField()
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='product_images/', null=True, blank=True)

    def __str__(self):
        return self.name
    
    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter(id__in = ids)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')
    uploaded_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Image of {self.product.name}"
    
    
    

class Order(models.Model):
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    state = models.CharField(max_length=255, null=True, blank=True)
    zip_code = models.CharField(max_length=10, null=True, blank=True)
    shipping_first_name = models.CharField(max_length=255, blank=True, null=True)
    shipping_last_name = models.CharField(max_length=255, blank=True, null=True)
    shipping_email = models.EmailField(blank=True, null=True)
    shipping_phone = models.CharField(max_length=20, blank=True, null=True)
    shipping_address = models.CharField(max_length=255, blank=True, null=True)
    shipping_country = models.CharField(max_length=255, blank=True, null=True)
    shipping_city = models.CharField(max_length=255, blank=True, null=True)
    shipping_state = models.CharField(max_length=255, blank=True, null=True)
    shipping_zip_code = models.CharField(max_length=10, blank=True, null=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES)
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=ORDER_CHOICES, default='Pending', blank=True, null=True)
    user = models.ForeignKey(customuser, on_delete=models.CASCADE, related_name='orders', null=False)


    def __str__(self):
        return f"Order {self.id} by {self.user.email if self.user else 'Unknown'}"
    @property
    def total_price(self):
        return sum(item.total_price for item in self.orderitem_set.all())    
    
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    user = models.ForeignKey(customuser, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} (x{self.quantity}) for Order {self.order.id} by {self.order.user.email if self.order.user else 'Unknown'}"



class CustomerReview(models.Model):
    user = models.ForeignKey(customuser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    profession = models.CharField(max_length=255)
    review = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Review by {self.user.first_name} {self.user.last_name} for {self.product.name}"
    
    
    
class Querries(models.Model):
    user = models.ForeignKey(customuser, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, null=True, blank=True)
    message = models.TextField(max_length=500)
    
    def __str__(self):
        return f"Query by {self.user.first_name} {self.user.last_name}"

MultiShop/base/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import customuser,Order, CustomerReview , Querries
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class SignupForm(forms.ModelForm):
    password = forms.CharField(label='Password', strip=False, widget=forms.PasswordInput)

    class Meta:
        model = customuser
        fields = ['first_name', 'last_name', 'father_name', 'username', 'email', 'password', 'gender', 'province', 'city', 'dob', 'phone', 'about', 'profile_pic']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class CustomAuthenticationForm(AuthenticationForm):
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if '@' in username:
            try:
                user = customuser.objects.get(email=username)
            except customuser.DoesNotExist:
                raise ValidationError(_('Invalid email or password.'), code='invalid')
        else:
            user = customuser.objects.filter(username=username).first()

        if user is not None and user.check_password(password):
            if user.is_active:
                self.user_cache = user
            else:
                raise ValidationError(_('This account is inactive.'), code='inactive')
        else:
            raise ValidationError(_('Invalid email or password.'), code='invalid')

        return self.cleaned_data


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = customuser
        fields = ['first_name', 'last_name', 'father_name', 'username', 'email', 'gender', 'province', 'city', 'dob', 'phone', 'about', 'profile_pic']


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name', 'last_name', 'email', 'phone', 'address', 'country', 
            'city', 'state', 'zip_code', 'shipping_first_name', 'shipping_last_name', 
            'shipping_email', 'shipping_phone', 'shipping_address', 'shipping_country', 
            'shipping_city', 'shipping_state', 'shipping_zip_code', 'payment_method', 'status'
        ]
        
        
class CustomerReviewForm(forms.ModelForm):
    class Meta:
        model = CustomerReview
        fields = ['profession', 'review', 'product']
        widgets = {
            'product': forms.HiddenInput(),
        }
        
class QuerriesForm(forms.ModelForm):
    class Meta:
        model = Querries
        fields = [
            'subject', 'message'
        ]
        
        widgets = {
            'subject': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the subject',
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your message',
            }),
        }

MultiShop/base/templates/base/bottombar.html
{% extends 'base/baseIndex.html' %}
{% load static %}


{% block content %}

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="{% url 'home' %}">
                                <img src="{% static 'img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">

                        <!-- In your base template where the navbar is defined -->
                        <div class="search">
                            <form action="{% url 'search' %}" method="GET" class="search">
                                {% csrf_token %}
                                <input type="text" placeholder="Search" aria-label="Search" name="query">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>


                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="{% url 'wishlist' %}" class="btn wishlist">
                                <i class="fa fa-heart"></i>
                                <span>({{request.session.wishlist.keys|length}})</span>
                            </a>
                            <a href="{% url 'cart' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>({{request.session.cart.keys|length}})</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End --> 


{% endblock content %}

MultiShop/base/templates/base/cart.html
{% extends 'base/baseIndex.html' %}

{% block content %}
{% load static %}
{% load cart %}
{% include 'base/navbar.html' %}
{% include 'base/bottombar.html' %}
        
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item active">Cart</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->
        
<!-- Cart Start -->
<div class="cart-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-page-inner">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Sno. </th>
                                    <th>Product Name</th>
                                    <th>Product Image</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th>Remove</th>
                                </tr>
                            </thead>
                            <tbody class="align-middle">
                                {% for product in products %}
                                <tr>
                                    <td> {{forloop.counter}}</td>
                                    <td>{{product.name}}</td>
                                    <td>
                                        <div class="img">
                                            <a href="{% url 'product_detail' product.id %}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                                        </div>
                                    </td>
                                    <td>{{product.price|currency}}</td>
                                    <td>{{product|cart_quantity:request.session.cart}}</td>
                                    <td>{{product|price_total:request.session.cart|currency}}</td>
                                    <td>
                                        <form action="" method="POST" class="d-inline">
                                            {% csrf_token %}
                                            <input type="hidden" name="product" value="{{ product.id }}">
                                            <button type="submit" name="remove" value="True" class="btn"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="7">No items in Cart.</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart-page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="coupon">
                                <input type="text" placeholder="Coupon Code">
                                <button>Apply Code</button>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="cart-summary">
                                <div class="cart-content">
                                    <h1>Cart Summary</h1>
                                    {% if request.session.cart %}
                                    <p>Sub Total<span>{{products|total_cart_price:request.session.cart|currency}}</span></p>
                                    {% comment %} <p>Shipping Cost<span>$1</span></p> {% endcomment %}
                                    <h2>Grand Total<span>{{products|total_cart_price:request.session.cart|currency}}</span></h2>
                                    {% else %}
                                    <p>Sub Total<span>0.00</span></p>
                                    <h2>Grand Total<span>0.00</span></h2>
                                    {% endif %}
                                </div>
                                <div class="cart-btn">
                                    {% comment %} <button>Update Cart</button> {% endcomment %}
                                    <button> <a href="{% url 'checkout' %}"> Checkout </a></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->

{% include 'base/footer.html' %}
{% endblock content %}

MultiShop/base/templates/base/change_password.html
{% extends 'base/baseIndex.html' %}
{% block content %}
<div class="container">
    <h2>Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Change Password</button>
        
    </form>
</div>
{% endblock %}

MultiShop/base/templates/base/checkout.html
{% extends "base/baseIndex.html" %}
{% block content %}
{% load static %}
{% include 'base/navbar.html' %}
{% include 'base/bottombar.html' %}

<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item active">Checkout</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Checkout Start -->
<div class="checkout">
    <div class="container-fluid"> 
        <form method="POST" action="{% url 'checkout' %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row">
                <div class="col-lg-8">
                    <div class="checkout-inner">
                        <div class="billing-address">
                            <h2>Billing Address</h2>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_first_name">First Name</label>
                                    {{ form.first_name }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_last_name">Last Name</label>
                                    {{ form.last_name }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_email">E-mail</label>
                                    {{ form.email }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_phone">Mobile No</label>
                                    {{ form.phone }}
                                </div>
                                <div class="col-md-12">
                                    <label for="id_address">Address</label>
                                    {{ form.address }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_country">Country</label>
                                    {{ form.country }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_city">City</label>
                                    {{ form.city }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_state">State</label>
                                    {{ form.state }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_zip_code">ZIP Code</label>
                                    {{ form.zip_code }}
                                </div>
                                <div class="col-md-12">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="shipto" name="ship_to_different_address">
                                        <label class="custom-control-label" for="shipto">Ship to different address</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="shipping-address" id="shipping-address" style="display: none;">
                            <h2>Shipping Address</h2>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_shipping_first_name">First Name</label>
                                    {{ form.shipping_first_name }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_shipping_last_name">Last Name</label>
                                    {{ form.shipping_last_name }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_shipping_email">E-mail</label>
                                    {{ form.shipping_email }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_shipping_phone">Mobile No</label>
                                    {{ form.shipping_phone }}
                                </div>
                                <div class="col-md-12">
                                    <label for="id_shipping_address">Address</label>
                                    {{ form.shipping_address }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_shipping_country">Country</label>
                                    {{ form.shipping_country }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_shipping_city">City</label>
                                    {{ form.shipping_city }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_shipping_state">State</label>
                                    {{ form.shipping_state }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_shipping_zip_code">ZIP Code</label>
                                    {{ form.shipping_zip_code }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="checkout-inner">
                        <div class="checkout-payment">
                            <div class="payment-methods">
                                <h1>Payment Methods</h1>
                                {% for payment_method in form.payment_method.field.choices %}
                                <div class="payment-method">
                                    <div class="custom-control custom-radio">
                                        <input type="radio" class="custom-control-input" id="payment-{{ forloop.counter }}" name="payment_method" value="{{ payment_method.0 }}">
                                        <label class="custom-control-label" for="payment-{{ forloop.counter }}">{{ payment_method.1 }}</label>
                                    </div>
                                    <div class="payment-content" id="payment-{{ forloop.counter }}-show">
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt orci ac eros volutpat maximus lacinia quis diam.
                                        </p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="checkout-btn">
                                <button type="submit" >Place Order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Checkout End -->

{% include 'base/footer.html' %}
{% endblock %}

MultiShop/base/templates/base/contactUs.html
{% extends "base/baseIndex.html" %}
{% block content %}
{% include 'base/navbar.html' %}

{% include 'base/bottombar.html'%}


<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item active">Contact</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Contact Start -->
<div class="contact">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4">
                <div class="contact-info">
                    <h2>Our Office</h2>
                    <h3><i class="fa fa-map-marker"></i>123 Office, Los Angeles, CA, USA</h3>
                    <h3><i class="fa fa-envelope"></i>office@example.com</h3>
                    <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                    <div class="social">
                        <a href=""><i class="fab fa-twitter"></i></a>
                        <a href=""><i class="fab fa-facebook-f"></i></a>
                        <a href=""><i class="fab fa-linkedin-in"></i></a>
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-info">
                    <h2>Our Store</h2>
                    <h3><i class="fa fa-map-marker"></i>123 Store, Los Angeles, CA, USA</h3>
                    <h3><i class="fa fa-envelope"></i>store@example.com</h3>
                    <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                    <div class="social">
                        <a href=""><i class="fab fa-twitter"></i></a>
                        <a href=""><i class="fab fa-facebook-f"></i></a>
                        <a href=""><i class="fab fa-linkedin-in"></i></a>
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-form">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_subject">Subject :</label>
                            {{ form.subject }}
                        </div>
                        <div class="form-group">
                            <label for="id_message">Message :</label>
                            {{ form.message }}
                        </div>
                        <div>
                            <button class="btn" type="submit">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="contact-map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3311.013017182858!2d73.04837771520892!3d33.68442038071012!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38df951488591941%3A0x795e4a99fd74d6c1!2sIslamabad%2C%20Pakistan!5e0!3m2!1sen!2sus!4v1689690364882!5m2!1sen!2sus" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->



{% include 'base/footer.html' %}

{% endblock content %}